SELECT
    ORDERID, 
    ORDERDATE,
    CUSTOMERID,
    EMPLOYEEID,
    STOREID,
    STATUS AS STATUSCD,
    CASE
        WHEN STATUS = '01' THEN 'In Progress'
        WHEN STATUS = '02' THEN 'Completed'
        WHEN STATUS = '03' THEN 'Cancelled'
        ELSE NULL
    END AS STATUSDESC,
    UPDATED_AT
FROM {{ ref('orders_base') }}
GROUP BY
    ORDERID, 
    ORDERDATE,
    CUSTOMERID,
    EMPLOYEEID,
    STOREID,
    STATUSCD,
    STATUSDESC,
    UPDATED_AT