SELECT 
    O.ORDERID,
    O.ORDERDATE,
    O.CUSTOMERID,
    O.EMPLOYEEID,
    O.STOREID,
    O.STATUSCD,
    O.STATUSDESC,
    O.UPDATED_AT,
    COUNT(OI.ORDERID) AS ORDERCOUNT,
    OI.REVENUE
FROM {{ ref('orders_stg')}} O
JOIN {{ ref('orderitems_stg')}} OI
    ON O.ORDERID = OI.ORDERID
GROUP BY 
    O.ORDERID,
    O.ORDERDATE,
    O.CUSTOMERID,
    O.EMPLOYEEID,
    O.STOREID,
    O.STATUSCD,
    O.STATUSDESC,
    O.UPDATED_AT,
    OI.REVENUE