{{ config(materialized = 'table') }}

WITH CUSTOMERREVENUE AS (
  SELECT 
    C.CUSTOMERID,
    C.CUSTOMERNAME,
    SUM(OS.ORDERCOUNT) AS ORDERCOUNT,
    SUM(OS.REVENUE) AS REVENUE
  FROM {{ ref('orders_fact')}} OS
  JOIN {{ ref('customer_stg')}} C
    ON OS.CUSTOMERID = C.CUSTOMERID
  GROUP BY C.CUSTOMERID, CUSTOMERNAME
)

SELECT 
  CUSTOMERID, 
  CUSTOMERNAME, 
  ORDERCOUNT, 
  REVENUE
FROM CUSTOMERREVENUE
