{{ config(materialized = 'table') }}

WITH CUSTOMERORDERS AS (
  SELECT 
    C.CUSTOMERID,
    C.CUSTOMERNAME,
    O.ORDERCOUNT
  FROM {{ ref('customer_stg') }} C
  JOIN {{ ref('orders_fact') }} O
    ON C.CUSTOMERID = O.CUSTOMERID
  GROUP BY C.CUSTOMERID, CUSTOMERNAME, O.ORDERCOUNT
  ORDER BY C.CUSTOMERID, CUSTOMERNAME, O.ORDERCOUNT DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT
FROM CUSTOMERORDERS
